apiVersion: v1
kind: Namespace
metadata:
  name: bird
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: birdapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaymineh/lifi-devops.git
    targetRevision: main
    path: helm-charts/birdapi
    helm:
      values: |
        ingress:
          enabled: false
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: bird
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true