replicaCount: 2
image:
  repository: jaymineh/birdimage
  tag: 0.7
  pullPolicy: Always
service:
  type: NodePort
  port: 4200
  targetPort: 30002

serviceAccount:
  create: true
  name: birdimage-sa
  annotations: {}
  automount: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70

ingress:
  enabled: false