replicaCount: 2
image:
  repository: jaymineh/birdimage
  tag: 0.4
service:
  type: NodePort
  port: 4200
  targetPort: 30002

autoscaling:
  enabled: true               # or true, depending on your needs
  minReplicas: 1                # Set appropriate minReplicas
  maxReplicas: 3                # Set appropriate maxReplicas
  targetCPUUtilizationPercentage: 80  # Adjust based on your requirements
  targetMemoryUtilizationPercentage: 70  # Adjust based on your requirements
