replicaCount: 2
image:
  repository: jaymineh/birdapi
  tag: 0.7
  pullPolicy: Always
service:
  type: NodePort
  port: 4201
  targetPort: 30001

serviceAccount:
  create: true 
  name: birdapi-sa
  annotations: {}
  automount: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70

ingress:
  enabled: false
