replicaCount: 2
image:
  repository: jaymineh/birdapi
  tag: 53592e5fdda67bd8602528b40b93a01ed84cce5d
  pullPolicy: Always
service:
  type: NodePort
  port: 4201
  targetPort: 30001
serviceAccount:
  create: true
  name: birdapi-sa
  annotations: {}
  automount: true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70
ingress:
  enabled: false
