apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-birdimage
  labels:
    app: birdimage
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: birdimage
  template:
    metadata:
      labels:
        app: birdimage
    spec:
      containers:
      - name: birdimage
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
