---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644

    - name: Configure kubeconfig permissions
      become: yes
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
        chown -R ubuntu:ubuntu /home/ubuntu/.kube
        chmod 600 /home/ubuntu/.kube/config

    - name: Set KUBECONFIG in bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/home/ubuntu/.kube/config'

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add Helm repos
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts \
        && helm repo add grafana https://grafana.github.io/helm-charts \
        && helm repo add argo https://argoproj.github.io/argo-helm \
        && helm repo update
      environment:
        HELM_HOME: "/home/ubuntu/.helm"

    - name: Check if repository is already cloned
      stat:
        path: /home/ubuntu/
      register: repo_cloned

    - name: Clone repository
      git:
        repo: https://github.com/jaymineh/lifi-devops.git
        dest: /home/ubuntu/
      when: not repo_cloned.stat.exists

    - name: Ensure /etc/grafana/provisioning/datasources directory exists
      file:
        path: /etc/grafana/provisioning/datasources
        state: directory
        mode: '0755'

    - name: Ensure /etc/grafana/provisioning/dashboards directory exists
      file:
        path: /etc/grafana/provisioning/dashboards
        state: directory
        mode: '0755'

    - name: Ensure /var/lib/grafana/dashboards directory exists
      file:
        path: /var/lib/grafana/dashboards
        state: directory
        mode: '0755'

    - name: Check if Grafana datasource file exists
      stat:
        path: /etc/grafana/provisioning/datasources/datasource.yml
      register: datasource_file

    - name: Copy Grafana datasource provisioning file
      copy:
        src: /home/ubuntu/lifi-devops/iac/ansible/grafana/dashboard/datasource.yml
        dest: /etc/grafana/provisioning/datasources/datasource.yml
        mode: '0644'
      when: not datasource_file.stat.exists

    - name: Check if Grafana dashboard provisioning file exists
      stat:
        path: /etc/grafana/provisioning/dashboards/dashboard.yml
      register: dashboard_provisioning_file

    - name: Copy Grafana dashboard provisioning file
      copy:
        src: /home/ubuntu/lifi-devops/iac/ansible/grafana/dashboard/dashboard.yml
        dest: /etc/grafana/provisioning/dashboards/dashboard.yml
        mode: '0644'
      when: not dashboard_provisioning_file.stat.exists

    - name: Check if Grafana dashboard JSON files exist
      file:
        path: /var/lib/grafana/dashboards
        state: directory
        mode: '0755'

    - name: Copy Grafana dashboard JSON files
      copy:
        src: "{{ item }}"
        dest: /var/lib/grafana/dashboards/
        mode: '0644'
      with_fileglob:
        - "/home/ubuntu/lifi-devops/iac/ansible/grafana/dashboard/*.json"
      when: true

    - name: Install Prometheus Operator with Helm
      shell: |
        helm upgrade --install prometheus-operator prometheus-community/kube-prometheus-stack \
        --set prometheus.service.type=NodePort \
        --set prometheus.service.nodePort=30003 \
        --namespace monitoring \
        --create-namespace \
        --wait
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

    - name: Install Grafana with Helm
      shell: |
        helm upgrade --install grafana grafana/grafana \
        --set adminPassword='adminpassword' \
        --set service.type=NodePort \
        --set service.nodePort=30004 \
        --namespace monitoring \
        --set extraVolumes[0].name=grafana-provisioning \
        --set extraVolumes[0].hostPath.path=/etc/grafana/provisioning \
        --set extraVolumes[0].hostPath.type=Directory \
        --set extraVolumes[1].name=grafana-dashboard-vol \
        --set extraVolumes[1].hostPath.path=/var/lib/grafana/dashboards \
        --set extraVolumes[1].hostPath.type=Directory \
        --set extraVolumeMounts[0].name=grafana-provisioning \
        --set extraVolumeMounts[0].mountPath=/etc/grafana/provisioning \
        --set extraVolumeMounts[1].name=grafana-dashboard-vol \
        --set extraVolumeMounts[1].mountPath=/var/lib/grafana/dashboards \
        --set persistence.enabled=true \
        --wait \
        --timeout 10m
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

    - name: Wait for Grafana pod to be ready
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=grafana  -n monitoring --timeout=120s
      changed_when: false

    - name: Generate bcrypt hash for custom password
      shell: |
        htpasswd -bnBC 10 "" admin | tr -d ':\n'
      register: argocd_password_hash
      no_log: true

    - name: Install ArgoCD with custom password
      shell: |
        helm upgrade --install argocd-demo argo/argo-cd \
        -f /home/ubuntu/lifi-devops/helm-charts/argocd-values.yaml \
        --set configs.secret.argocdServerAdminPassword="$ARGOCD_PASSWORD_HASH" \
        --namespace argocd \
        --create-namespace \
        --wait
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
        ARGOCD_PASSWORD_HASH: "{{ argocd_password_hash.stdout }}"

    - name: Wait for ArgoCD pod to be ready
      shell: kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=120s
      changed_when: false

    - name: Get EC2 Public IP
      shell: curl -s http://169.254.169.254/latest/meta-data/public-ipv4
      register: ec2_ip
      changed_when: false

    - name: Generate ArgoCD Token with Correct IP
      shell: |
        argocd login $ARGOCD_SERVER \
          --username admin \
          --password admin \
          --grpc-web --insecure
        argocd account generate-token
      environment:
        ARGOCD_SERVER: "{{ ec2_ip.stdout }}:30005"
      register: argocd_token
      no_log: true

    - name: Display Token
      debug:
        msg: |
          Add this token to GitHub Secrets as ARGOCD_TOKEN:
          {{ argocd_token.stdout }}
        
    # - name: Deploy birdImage API using Helm
    #   shell: |
    #     helm upgrade --install birdimageapi /home/ubuntu/lifi-devops/helm-charts/birdimageapi/ \
    #     --namespace bird \
    #     --create-namespace
    #   environment:
    #     KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

    # - name: Deploy bird API using Helm
    #   shell: |
    #     helm upgrade --install birdapi /home/ubuntu/lifi-devops/helm-charts/birdapi/ \
    #     --namespace bird \
    #   environment:
    #     KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Ensure SSH uses key-based authentication only
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Restart SSH service to apply changes
      systemd:
        name: ssh
        state: restarted

    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present