name: CI/CD Pipeline

on:
    push:
        branches: [main]
        paths:
            - 'bird/**'
            - 'birdImage/**'
            - 'iac/**'
            - 'helm-charts/**'
            - '.github/workflows/**'

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
    ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}

jobs:
    security-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Golang codescan with Gosec
              uses: securego/gosec@master
              continue-on-error: true
              with:
                args: './bird/... ./birdImage/...'

            - name: Terraform codescan with tfsec
              uses: aquasecurity/tfsec-action@v1.0.0
              continue-on-error: true
              with:
                args: './iac/...'

    determine-changes:
        needs: security-scan
        runs-on: ubuntu-latest
        outputs:
            birdapi_changed: ${{ steps.check_changes.outputs.birdapi_changed }}
            birdimageapi_changed: ${{ steps.check_changes.outputs.birdimageapi_changed }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Check for changes
              id: check_changes
              run: |
                git diff --name-only HEAD^ HEAD > changes.txt
                echo "Changed files:"
                cat changes.txt
                birdapi_changed=$(grep -q '^bird/' changes.txt && echo 'true' || echo 'false')
                birdimageapi_changed=$(grep -q '^birdImage/' changes.txt && echo 'true' || echo 'false')
                echo "Debug: Bird API changed: $birdapi_changed"
                echo "Debug: BirdImage API changed: $birdimageapi_changed"
                echo "birdapi_changed=$birdapi_changed" >> $GITHUB_OUTPUT
                echo "birdimageapi_changed=$birdimageapi_changed" >> $GITHUB_OUTPUT

            - name: Debug Outputs
              run: |
                echo "Outputs set in GITHUB_OUTPUT:"
                cat $GITHUB_OUTPUT

    build-bird:
        needs: determine-changes
        runs-on: ubuntu-latest
        if: needs.determine-changes.outputs.birdapi_changed == 'true'
        steps:

            - name: Debug Condition
              run: |
                echo "BIRD API changed value: ${{ needs.determine-changes.outputs.birdapi_changed }}"

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ env.DOCKERHUB_USERNAME }}
                password: ${{ env.DOCKERHUB_TOKEN }}

            - name: Build and Push Bird API
              uses: docker/build-push-action@v4
              with:
                  context: ./bird
                  push: true
                  tags: ${{ env.DOCKERHUB_USERNAME }}/bird:${{ github.sha }}

    build-birdimage:
        needs: determine-changes
        runs-on: ubuntu-latest
        if: needs.determine-changes.outputs.birdapi_changed == 'true'
        steps:
            - name: Debug Condition
              run: |
                echo "BIRD API changed value: ${{ needs.determine-changes.outputs.birdapi_changed }}"

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ env.DOCKERHUB_USERNAME }}
                password: ${{ env.DOCKERHUB_TOKEN }}

            - name: Build and Push Bird Image API
              uses: docker/build-push-action@v4
              with:
                  context: ./birdImage
                  push: true
                  tags: ${{ env.DOCKERHUB_USERNAME }}/birdimage:${{ github.sha }}
              
    deploy:
        needs: [build-bird, build-birdimage, determine-changes]
        runs-on: ubuntu-latest
        if: |
          needs.determine-changes.outputs.birdapi_changed == 'true' ||
          needs.determine-changes.outputs.birdimageapi_changed == 'true'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install yq
              run: |
                wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/local/bin/yq
                chmod +x /usr/local/bin/yq

            - name: Update Helm chart values
              if: |
                needs.determine-changes.outputs.birdapi_changed == 'true' ||
                needs.determine-changes.outputs.birdimageapi_changed == 'true'
              run: |

                if [[ "${{ needs.determine-changes.outputs.birdapi_changed }}" == "true" ]]; then
                    # Update the image tag in the Helm values for birdapi
                    yq eval '.image.tag = "${{ github.sha }}"' -i helm-charts/birdapi/values.yaml
                    git add helm-charts/birdapi/values.yaml
                fi


                if [[ "${{ needs.determine-changes.outputs.birdimageapi_changed }}" == "true" ]]; then
                    # Update the image tag in the Helm values for birdimageapi
                    yq eval '.image.tag = "${{ github.sha }}"' -i helm-charts/birdimageapi/values.yaml
                    git add helm-charts/birdimageapi/values.yaml
                fi

            - name: Commit and push changes
              run: |
                if [[ -n "$(git status --porcelain)" ]]; then
                    git config --global user.name 'GitHub Actions'
                    git config --global user.email 'github-actions@github.com'
                    git commit -m "Update image tags to ${{ github.sha }}"
                    git push
                fi

            - name: Trigger ArgoCD sync
              run: |
                if [[ "${{ needs.determine-changes.outputs.birdapi_changed }}" == "true" ]]; then
                  curl -sS -k -X POST \
                    -H "Authorization: Bearer ${{ env.ARGOCD_TOKEN }}" \
                    "${{ env.ARGOCD_SERVER }}/api/v1/applications/birdapi/sync"
                fi

                if [[ "${{ needs.determine-changes.outputs.birdimageapi_changed }}" == "true" ]]; then
                  curl -sS -k -X POST \
                    -H "Authorization: Bearer ${{ env.ARGOCD_TOKEN }}" \
                    "${{ env.ARGOCD_SERVER }}/api/v1/applications/birdimageapi/sync"
                fi


            # - name: Download built APIs
            #   uses: actions/download-artifact@v3
            #   with:
            #     name: built-apis

            # - name: Update Helm charts
            #   run: |
            #     if [ -f built-apis.txt ]; then
            #         while read -r api; do
            #             values_file=
            #             image_tag="${{ github.sha }}"
            #             yq eval ".image.tag = \"$image_tag\"" -i $values_file
            #             yq eval ".image.repository = \"${{ env.DOCKERHUB_USERNAME }}/$api\"" -i $values_file
            #         done < built-apis.txt
            #     fi



            
