name: CI/CD Pipeline

on:
    push:
        branches: [main]
        paths:
            - 'bird/**'
            - 'birdImage/**'
            - 'iac/**'
            - 'helm-charts/**'
            - '.github/workflows/**'

env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: your-aws-region
    EC2_IP: ${{ secrets.EC2_IP }}
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
    security-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Golang codescan with Gosec
              uses: securego/gosec@master
              continue-on-error: true
              with:
                args: './bird/... ./birdImage/...'

            - name: Terraform codescan with tfsec
              uses: aquasecurity/tfsec-action@v1.0.0
              continue-on-error: true
              with:
                working-directory: iac

    determine-changes:
        needs: security-scan
        runs-on: ubuntu-latest
        outputs:
            bird-api: ${{ steps.check-bird-api.outputs.changed }}
            birdimage-api: ${{ steps.check-birdimage-api.outputs.changed }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 2

            - name: Check for changes
              id: check_changes
              run: |
                git diff --name-only HEAD^ HEAD > changes.txt
                echo "bird-api=$(grep -q 'bird/' changes.txt && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
                echo "birdimage-api=$(grep -q 'birdImage/' changes.txt && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT


            
